import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../componets/NavBar";
import { Toaster } from "react-hot-toast";
import NeaxtAuthProvider from "@/Providers/NeaxtAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`max-w-7xl mx-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NeaxtAuthProvider>
          <Navbar />
          <Toaster />
          {children}
        </NeaxtAuthProvider>
      </body>
    </html>
  );
}
